name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      with:
        format: "pretty-printer"
        # outputFile: results.sarif
        frameworks: "nsa"
        severityThreshold: "critical"
        # # Optional - Add Kubescape cloud account ID.
        # account: ${{secrets.KUBESCAPE_ACCOUNT}}
