name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd test-stdout-program && go build && ls .

    - name: Run test STDOUT/STDERR program
      run: ls . && cd test-stdout-program && ./main

    - uses: kubescape/github-action@main
      with:
        frameworks: "nsa"
        format: "pretty-printer"
        files: "./online-boutique/"
        # outputFile: "results"
        severityThreshold: "critical"
        # # Optional - Add Kubescape cloud account ID.
        # account: ${{secrets.KUBESCAPE_ACCOUNT}}

    - name: Check dir
      run: ls .
