name: Suggest autofixes with Kubescape
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6
    - uses: vladklokun/github-action@feat-support-autofixing
      with:
        files: ${{ steps.changed-files.outputs.all_changed_files }}
        fixFiles: true
        format: "sarif,json"
    - uses: peter-evans/create-pull-request@v4
      with:
        add-paths: |
          *.yaml
          *.yml
        commit-message: Add Security
        title: "chore: fix K8s misconfigurations"
        body: |
          Kubescape added some straightforward fixes to enhance security of this change.
          You may still need to add some fixes manually that are not conclusive.
        base: ${{ github.head_ref }}
        branch: kubescape-auto-fix-${{ github.head_ref || github.ref_name }}
        delete-branch: true
