name: Suggest autofixes with Kubescape
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6
    - uses: vladklokun/github-action@feat-support-autofixing
      with:
        files: ${{ steps.changed-files.outputs.all_changed_files }}
        fixFiles: true
        format: "sarif,json"
        severityThreshold: "critical"
    - uses: peter-evans/create-pull-request@v4
      with:
        add-paths: |
          *.yaml
        commit-message: "chore: fix K8s misconfigurations"
        title: "[Kubescape] chore: fix K8s misconfigurations"
        body: |
          # What this PR changes

          https://github.com/kubescape/kubescape has found misconfigurations in
          the targeted branch. This PR fixes the misconfigurations that have
          automatic fixes available. You may still need to fix
          misconfigurations that do not have automatic fixes.
        base: ${{ github.head_ref }}
        branch: kubescape-auto-fix-${{ github.head_ref || github.ref_name }}
        delete-branch: true
