name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd test-stdout-program && go build

    - name: Run test STDOUT/STDERR program
      run: ./main

    - uses: kubescape/github-action@main
      with:
        format: "pretty-printer"
        # outputFile: results.sarif
        frameworks: "nsa"
        severityThreshold: "critical"
        # # Optional - Add Kubescape cloud account ID.
        # account: ${{secrets.KUBESCAPE_ACCOUNT}}
